name: Python-AI Application

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          #Stop the build if there are python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          #Exit zero treats all errors as warnings. The GitHub editor is 127 characters wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest -v

      # - name: Deploy to AWS/HEROKU
      #   env:
      #     AWS_API_TOKEN: ${{ secrets.AWS_API_TOKEN }}
      #     AWS_APP_NAME: ${{ secrets.AWS_APP_NAME }}
      #   if: github.ref == 'refs/heads/main' && job.status == 'success'
      #   run: |
      #     git remote add AWS <<AWS project URL>>
      #     git push AWS HEAD:main -f
      #
      # CREATE THE PROCFILE